# Site settings
title: The Grapes of Math Interactive Examples
#email: IDontWantMoreSpam@chrisnolan.ca
description: > # this means to ignore newlines until "baseurl:"
  Interactive programs based on topics in Alex Bello's The Grapes of Math book.  
  Javascript programs displayed via Khan Academy's CS tools that help you to
  understand the math and more.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  ChrisNolan

# Build settings
markdown: kramdown

#
permalink: none